// Simple initialization script for the ROSAgo backend
console.log('ROSAgo Backend Initialization Script');
console.log('=================================');
console.log('');
console.log('To set up the backend, please follow these steps:');
console.log('');
console.log('1. Make sure Node.js (version 18 or higher) is installed on your system');
console.log('2. Make sure PostgreSQL and Redis are running');
console.log('3. Navigate to the backend directory:');
console.log('   cd backend');
console.log('4. Install dependencies:');
console.log('   npm install');
console.log('5. Set up environment variables by copying .env.example to .env and adjusting values');
console.log('6. Generate Prisma client:');
console.log('   npm run prisma:generate');
console.log('7. Run database migrations:');
console.log('   npm run prisma:migrate');
console.log('8. Seed the database with initial data:');
console.log('   npm run seed');
console.log('9. Start the development server:');
console.log('   npm run start:dev');
console.log('');
console.log('For production deployment:');
console.log('- Build the application: npm run build');
console.log('- Start the production server: npm run start:prod');
console.log('- Run workers: npm run worker');
console.log('');
console.log('For Docker development environment:');
console.log('docker compose -f docker-compose.dev.yml up');